from snakemake.utils import min_version

min_version("7.32.4")


configfile: "config/config.yaml"


# Parameters
MATRIX_PROB = config["PWM-SCAN"]["MATRIX_PROB"]
MATRIX_SCAN = config["PWM-SCAN"]["MATRIX_SCAN"]


rule compile_pwmscan:
    message:
        """
        Compiles PWMScan. Note c99 flag.
        Installs into resources/software by default.
        """
    input:
        prob=workflow.source_path(f"../{MATRIX_PROB}"),
        scan=workflow.source_path(f"../{MATRIX_SCAN}"),
    output:
        compiled_prob="resources/software/PWMScan/matrix_prob",
        compiled_scan="resources/software/PWMScan/matrix_scan",
    log:
        stdout="workflow/logs/compile_pwmscan.stdout",
        stderr="workflow/logs/compile_pwmscan.stderr",
    threads: 2
    shell:
        """
        gcc -std=c99 -o {output.compiled_prob} {input.prob}
        gcc -std=c99 -o {output.compiled_scan} {input.scan}
        """
