from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Modules
module pwmscan:
    snakefile:
        "rules/pwmscan.smk"
    config:
        config["PWMScan"]


# Import modules
use rule * from pwmscan as pwmscan_*


###
# Rules
###


rule all:
    message:
        """
        DEPLOYING PWMScan...
        """
    input:
        rules.pwmscan_all.input,
    default_target: True
